runtime: nodejs14

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /desktop_pc
  static_dir: dist/desktop_pc

- url: /assets
  static_dir: dist/assets

- url: /planet
  static_dir: dist/planet

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html



